#  method_name
method_name: 'EE_AT_AWP'

# Training
arch: 'PreActResNet18_EE_BPDA_3'

start_epoch: 0
epochs: 200

batch_size: 100

l2: 0
l1: 0

lr_schedule: 'piecewise'

lr: 0.1

workers: 2
pin_memory: true

# epsilon: 8

attack_iters: 10
attack_iters_test: 20

restarts: 1

pgd_alpha: 2.0

norm: 'l_inf'

seed: 0

half: false
width_factor: 10

cutout: false

chkpt_iters: 10

# awp_gamma: 0.01
awp_gamma: 0.005
awp_warmup: 0

momentum: 0.9
weight_decay: 0.0005

random: true

# Attack
# 16 /255
epsilon: 0.062745098039216

num_steps_1: 10
# 2/255
step_size_1: 0.007843137254902

num_steps_2: 20

print_freq: 50

cize: 64

alpha: 0
sigma: 1.0

w: 1.0
r: 8
gf: false
low: 38.0
high: 76.0